# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
import numpy as np
# help(np.random.uniform)
arr = np.random.uniform(0, 20, size = (4,7))
print(f'Массив: {arr}')
a = 1/(arr.max()-arr.min())
b = -arr.min() * a
datanorm = a * arr + b
print(f'Нормализованный массив: {datanorm}')

Массив: [[12.31032942  7.17180848  4.67731639 12.50024122 15.22161323  4.72713487
   0.97928726]
 [ 3.44154424  2.16079293 18.91674907 10.24420128 18.49066127 15.56201007
   1.96070277]
 [10.18359524  4.53213385 10.16260281  6.93641546 15.87720706  9.83624259
  16.03856434]
 [ 9.29783262  2.93866013  3.90263679  1.60061541 17.04125376 17.57757484
  18.04247932]]
Нормализованный массив: [[0.63169708 0.3452284  0.20616234 0.64228452 0.79399896 0.20893968
  0.        ]
 [0.13726897 0.06586805 1.         0.51651199 0.97624593 0.81297582
  0.05471318]
 [0.51313324 0.19806852 0.51196293 0.33210541 0.83054782 0.4937686
  0.83954337]
 [0.46375265 0.10923356 0.16297454 0.03463858 0.89544255 0.92534204
  0.95126012]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
arr = np.random.randint(0, 11, size=(8, 10))
print(arr)
print(f'Индекс строки: {np.sum(arr, axis=1).argmin()}')
print("Строка:", arr[np.sum(arr, axis=1).argmin()])

[[ 0  1  0  1  3  0  1  2  2  0]
 [ 8  2  1  6  8  3  4  5  1 10]
 [ 2  3  7  7  5  4  4  1  4  7]
 [ 9  3  7  1  4  5  9  4 10  4]
 [ 7  4  1  4  5  2  9 10  1  8]
 [ 2  9  6  6  1  5  6 10  3  1]
 [ 4  3  4  6  4  0  7  6  3  6]
 [ 9  6  1  9 10 10  3  5  9  7]]
Индекс строки: 0
Строка: [0 1 0 1 3 0 1 2 2 0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
# Примеры двух одномерных векторов:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
print('Вектора для примера: ', vec1, vec2)
print('Евклидово расстояние: ', np.linalg.norm(vec1 - vec2))

Вектора для примера:  [1 2 3] [4 5 6]
Евклидово расстояние:  5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [6]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
print(X)

[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [7]:
file = np.loadtxt('minutes_n_ingredients.csv', delimiter = ',', dtype = np.int32, skiprows = 1)
print(file[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
print(f'Среднее значение: {abs(np.sum(file[:, 1:], axis = 0)/np.size(file[:, 1:], axis = 0))}')
# Мoжно использовать mean: print(np.mean(file[:,1:], axis=0))
print(f'Минимальные значения по столбцам: 1-го - {np.min(file[:, 1])}, 2-го - {np.min(file[:, 2])}')
print(f'Максимальные значения по столбцам: 1-го - {np.max(file[:, 1])}, 2-го - {np.max(file[:, 2])}')
print(f'Медианы по столбцам: 1-го - {np.median(file[:, 1])}, 2-го - {np.median(file[:, 2])}')

Среднее значение: [2.13486713e+04 9.05528000e+00]
Минимальные значения по столбцам: 1-го - 0, 2-го - 1
Максимальные значения по столбцам: 1-го - 2147483647, 2-го - 39
Медианы по столбцам: 1-го - 40.0, 2-го - 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [9]:
quantile_75 = np.quantile(file[:, 1], 0.75)
file[:, 1] = np.minimum(file[:, 1], quantile_75)
# Ограничение значения квантилем означает, что мы применяем такой метод, который позволяет нам ограничить значения нашего 
# набора данных таким образом, чтобы по крайней мере 75% значений были меньше или равны этому ограничивающему значению'''

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
count = np.sum(file[:, 1] == 0)
print(f'Таких рецептов {count}')
file[file[:, 1] == 0, 1] = 1

Таких рецептов 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
unique_recipes = np.unique(file[:, 1:], axis=0)
num_unique_recipes = len(unique_recipes)
print("Количество уникальных рецептов:", num_unique_recipes)

Количество уникальных рецептов: 1135


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [12]:
unik_ingredient_counts = np.unique(file[:, 2])
print("Количество различных значений количества ингредиентов:", len(unik_ingredient_counts))
print("Различные значения количества ингредиентов:", unik_ingredient_counts)

Количество различных значений количества ингредиентов: 37
Различные значения количества ингредиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
filtered_file = file[file[:, 2] <= 5]
print('Такой массив: \n', filtered_file)

Такой массив: 
 [[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [14]:
max_ingredients_na_minute = np.max(file[:, 2] / file[:, 1])
mean_ingredients_na_minute = np.mean(file[:, 2] / file[:, 1])
print("Среднее количество ингредиентов на одну минуту:", mean_ingredients_na_minute)
print("Максимальное количество ингредиентов на одну минуту:", max_ingredients_na_minute)

Среднее количество ингредиентов на одну минуту: 0.3983000355850672
Максимальное количество ингредиентов на одну минуту: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [15]:
top100 = file[file[:, 1].argsort()[-100:]]
print("Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:", np.mean(top100[:, 2]))

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [16]:
sluch_indikat = np.random.choice(file.shape[0], size = 10, replace = False)
print('Информация о 10 различных рецептах: \n', file[sluch_indikat])

Информация о 10 различных рецептах: 
 [[ 31497     60     15]
 [ 50026     65      5]
 [358053     41     11]
 [ 14601     65      5]
 [319663      5      7]
 [ 71393     10      2]
 [405050     65     14]
 [202869     30     12]
 [399370      3      4]
 [186299     65     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [17]:
sr_procent = np.mean(file[:, 2])
count_recept = np.sum(file[:, 2] < sr_procent)
print(f"Процент рецептов, у которых количество ингредиентов меньше среднего: {count_recept/len(file)*100}%")

Процент рецептов, у которых количество ингредиентов меньше среднего: 58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [18]:
simple_recipe = np.zeros((len(file), 1), dtype=np.int32)
# np.zeros(shape) создает новый массив, заполненный нулями, указанной формы (shape)
simple_recipe[(file[:, 1] <= 20) & (file[:, 2] <= 5)] = 1
file_with_simple_column = np.hstack((file, simple_recipe))
# np.hstack() используется для горизонтального соединения массивов
print("Этот датасет: \n", file_with_simple_column)

Этот датасет: 
 [[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [19]:
simple_recipe_count = np.sum(simple_recipe)
procent_simple_recipes = (simple_recipe_count / len(file)) * 100
print(f"Процент 'простых' рецептов в датасете: {procent_simple_recipes}%")

Процент 'простых' рецептов в датасете: 9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [20]:
short_recept = file[file[:, 1] < 10]
standard_recept = file[(file[:, 1] >= 10) & (file[:, 1] < 20)]
long_recept = file[file[:, 1] >= 20]
max_length = min(len(short_recept), len(standard_recept), len(long_recept))
short_recept = short_recept[:max_length]
standard_recept = standard_recept[:max_length]
long_recept = long_recept[:max_length]
print(file[:5])
three_dimensional_array = np.array([short_recept, standard_recept, long_recept])
print("Форма полученного массива:", three_dimensional_array.shape)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]
Форма полученного массива: (3, 7588, 3)
